apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-k8s
  labels:
    app: simple-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-k8s
  template:
    metadata:
      labels:
        app: simple-k8s
    spec:
      containers:
        - name: simple-k8s
          image: davidgrieser/simple-k8s
          ports:
            - containerPort: 8080
          envFrom:
          - configMapRef:
              name: simple-k8s-config
